# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  pull_request:
    branches: [ "dev" ]
jobs:
  build:

    runs-on: ubuntu-latest
    name: syntax-check

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Before SHA
      run: | 
          echo "Before SHA: ${{ github.event.before }}"

    - name: Set boolean to true if folder changed
      run: |
        folder_changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep './TestProject2')
        if [ -n "$folder_changed" ]; then
          echo "Folder changed. Set boolean to true."
          echo "BOOL_VARIABLE=true" >> $GITHUB_ENV
        else
          echo "No change in folder."
        fi
    
    - name: Setup .NET
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet restore
    - name: Build
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet build --no-restore
    - name: Test
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet test --no-build --verbosity normal
