# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  pull_request:
    branches: [ "dev" ]
jobs:
  build:

    runs-on: ubuntu-latest
    name: syntax-check

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Get changes
      run: changes=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- './TestProject2') 
          if [ -n "$changes" ]; then
            echo "Changes detected in your-folder."
            echo "::set-output name=changes_exist::true"
          else
            echo "No changes detected in your-folder."
            echo "::set-output name=changes_exist::false"
          fi

          
     

    - name: Get Before SHA
      run: | 
          echo "Before SHA: ${{ github.event.before }}"

    - name: Setup .NET
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet restore
    - name: Build
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet build --no-restore
    - name: Test
      if: ${{ steps.check_changes.outputs.changes_exist == 'true' }}
      run: dotnet test --no-build --verbosity normal
