# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  pull_request:
    branches: [ "dev" ]
jobs:
  build:

    runs-on: ubuntu-latest
    name: syntax-check

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
          fetch-depth: 2
    
    - name: Get changes
      id: get-changes
      run: |
          changes=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- './TestProject2')
          if [ -n "$changes" ]; then
            echo "changes_exist=true" >> $GITHUB_OUTPUT
            echo "Changes detected in your-folder."
          else
            echo "No changes detected in Au2office.core"
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi

    - name: Setup .NET
      if: ${{ steps.get-changes.outputs.changes_exist == 'true' }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      if: ${{ steps.get-changes.outputs.changes_exist == 'true' }}
      run: dotnet restore
    - name: Build
      if: ${{ steps.get-changes.outputs.changes_exist == 'true' }}
      run: dotnet build --no-restore
    - name: Test
      if: ${{ steps.get-changes.outputs.changes_exist == 'true' }}
      run: dotnet test --no-build --verbosity normal
