# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Generate and Coverage Report

on:
  schedule:
    - cron: '0 18 * * 4'  # Runs every Thursday at 7 pm in Central European Time (UTC+1)

jobs:
  generate_and_send_report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and generate coverage
      run: |
        dotnet tool install --global coverlet.console
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Check coverage file
      run: test -e TestProject2/coverage.cobertura.xml

    - name: ReportGenerator
      if: success()
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: TestProject2/coverage.cobertura.xml
        targetdir: coverage

    - name: Upload File as Artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: generated-file
        path: coverage/index.html

    - name: Notify Discord
      if: success()
      env:
        DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1176974224586448997/BpjGhFnnJc3x2SpLmVXZpVFcSXOlKv7XvilaL0wAPAN1lBEmOpzoG8O8P3TG9QAhWjt3"
      run: |
        run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"GitHub Action completed! View details [here]($run_url)\"}" \
        "https://discord.com/api/webhooks/1176974224586448997/BpjGhFnnJc3x2SpLmVXZpVFcSXOlKv7XvilaL0wAPAN1lBEmOpzoG8O8P3TG9QAhWjt3"


