# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Generate and Coverage Report

on:
  push:
    branches:
      - dev  # Adjust this to your branch name

jobs:
  generate_and_send_report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        dotnet-quality: 'ga'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and generate coverage
      run: |
        dotnet tool install --global coverlet.console
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Check coverage file
      run: test -e TestProject2/coverage.cobertura.xml

    - name: Generate Coverage Report
      if: success()
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.7.0
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage

    - name: List files in the repository
      if: success()
      run: |
        ls ${{ github.workspace }}   

    - name: ReportGenerator
      if: success()
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: /coverage.cobertura.xml
        targetdir: coverage

    - name: Notify Discord
      if: success()
      env:
        DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1176974224586448997/BpjGhFnnJc3x2SpLmVXZpVFcSXOlKv7XvilaL0wAPAN1lBEmOpzoG8O8P3TG9QAhWjt3"
      run: |
        run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        curl -X POST -H "Content-Type: application/json" -d "{\"content\":\"GitHub Action completed! View details [here]($run_url)\"}" \
        "https://discord.com/api/webhooks/1176974224586448997/BpjGhFnnJc3x2SpLmVXZpVFcSXOlKv7XvilaL0wAPAN1lBEmOpzoG8O8P3TG9QAhWjt3"


