name: Generate and Coverage Report

on:
  push:
    branches:
      - dev  # Adjust this to your branch name

jobs:
  generate_and_send_report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and generate coverage
      run: |
        dotnet tool install --global coverlet.console
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
    
    - name: Check coverage file
      run: test -e TestProject2/coverage.cobertura.xml

    - name: Generate Coverage Report
      if: success()
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.7.0
        reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage
